- name: Check if backup user exists all mongo services
  command: '{{ mongodb_shell.get_user }}'
  register: backupuserquery
  vars:
    mongo_host: '{{ item.0 }}'
    mongo_port: '{{ item.1 }}'
    mongodb_ports:
    - '{{ mongoc_port }}'
    - '{{ mongod_port }}'
    - '{{ mongos_port }}'
  loop: '{{ ansible_play_batch|product(mongodb_ports)|list }}'
  loop_control:
    label: '{{ item.0 }}'
  run_once: true
  no_log: true

- name: Set user permissions as fact
  set_fact:
    backup_user_roles: '{{ item.stdout | from_json | json_query("roles[*]") }}'
    matching_roles: '{{ item.stdout | from_json | json_query(jq) }}'
  vars:
    jq: roles[?contains(role,`backup`) == `true`].role
  loop: '{{ backupuserquery.results }}'
  loop_control:
    label: '{{ item.item }}'
  run_once: true

- name: Verify backup user permissions
  assert:
    that:
    - matching_roles == ['backup']
    success_msg: The backup user has all the necessary permissions to perform backup
      tasks.
    fail_msg: >-
      The backup user does not have the necessary permissions to perform the backup
      tasks. Try adding it to the built-in backup role in your database.
      are the current roles for this user: {{ backup_user_roles }}
  run_once: true
