- name: MONGOS | Restarting mongos balancers
  command: '{{ mongodb_shell.start_mongos_balancer }}'
  vars:
    mongo_port: '{{ mongos_port }}'
    mongo_host: '{{ item }}'
  loop: '{{ ansible_play_batch }}'
  run_once: true

- name: MONGOS | Getting mongos balancer status
  shell: '{{ mongodb_shell.check_mongos_balancer_status }}'
  register: mongosbalancerstatus
  vars:
    mongo_port: '{{ mongos_port }}'
    mongo_host: '{{ item }}'
  loop: '{{ ansible_play_batch }}'
  run_once: true
  until: mongosbalancerstatus.stdout.find("Currently enabled"':'"  yes") != -1
  retries: 5
  delay: 3

- name: MONGOS | Showing mongos balancer status after restart
  debug:
    msg: '{{ item.stdout | from_yaml }}'
  loop: '{{ mongosbalancerstatus.results }}'
  loop_control:
    label: '{{ item.item }}'
  run_once: true
